apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hospital-api
  namespace: frontdoor
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: jeffgbutler/hospital-api@sha256:7b8d8e2bbd5830ccc446a47a751fd1bfd3d42526feda4ebf52f04c3ef0527d43
          ports:
            - containerPort: 8090
          env:
            - name: "spring.profiles.active"
              value: "kubernetes"
