apiVersion: v1
kind: Service
metadata:
  name: hapi-fhir
  namespace: tanzu-hospital
spec:
  type: LoadBalancer
  ports:
    - name: "http"
      port: 80
      targetPort: 8080
  selector:
    app: hapi-fhir
