apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tanzu-hospital-frontdoor-knative-psp
  namespace: frontdoor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cnr-restricted
subjects:
  - kind: Group
    name: system:serviceaccounts:frontdoor
