apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: tanzu-hospital
spec:
  template:
    spec:
      containers:
        - image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOSTS
              value: "tanzu-hospital-mysql-mariadb"
